<div class="banner main-bg">
    <div class="logo">
        <i class="en iconfont main-color">&#xe610;</i>
        <i class="cn iconfont main-color">&#xe611;</i>
    </div>
    <div class="slogan">
        <i class="en iconfont main-color">&#xe612;</i>
    </div>
    <div class="menu">
        <a href="#">首页</a>
        <a href="#">云出单</a>
        <a href="#">App</a>
        <a href="#">服务</a>
        <a href="#">关于我们</a>
    </div>
</div>