<div class="footer main-bg">
    <div class="info">
        <div class="footer-menu">
            <div class="footer-menu-top">
                <div class="main-color"><b>联系电话：</b>0757-86231983</div>
                <div class="main-color"><b>通讯地址：</b>佛山市南海区桂城街道叠北庆云沙洲围地段5号之二十五</div>
                <div class="main-color"><b>企业邮箱：</b>company@lkesy.com</div>
            </div>
            <div class="footer-menu-bottom">
                <div class="col col-1">
                    <div class="caption main-color">领客易选Web</div>
                    <a href="#" class="main-color">平台介绍</a>
                    <a href="#" class="main-color">登录平台</a>
                </div>
                <div class="col col-2">
                    <div class="caption main-color">领客易选App</div>
                    <a href="#" class="main-color">产品功能</a>
                    <a href="#" class="main-color">App下载</a>
                </div>
                <div class="col col-3">
                    <div class="caption main-color">关于我们</div>
                    <a href="#" class="main-color">关于企业</a>
                    <a href="#" class="main-color">联系我们</a>
                </div>
                <div class="col col-4">
                    <div class="caption main-color">服务</div>
                    <a href="#" class="main-color">服务与支持</a>
                    <a href="#" class="main-color">疑问解答</a>
                </div>
            </div>
        </div>
        <div class="footer-logo">
            <div class="footer-logo-top">
                <div class="logo">
                    <i class="en iconfont main-color">&#xe610;</i>
                    <i class="cn iconfont main-color">&#xe611;</i>
                </div>
                <div class="qrcode default-bg default-color"><i class="iconfont">&#xe615;</i>微信公众号</div>
            </div>
            <div class="footer-ipc main-color">
                <div><a>用户协议</a>|<a>隐私条例</a></div>
                <div><a>Copyright © 2019 佛山领客易选科技服务有限公司，保留所有权利。</a><a href="http://www.beian.miit.gov.cn" target="_blank" class="main-color">粤ICP备19043047号-1</a>
                </div>
            </div>
        </div>
    </div>
</div>