<div class="banner default-bg">
    <div class="logo default-bg">
        <i class="en iconfont default-color">&#xe610;</i>
        <i class="cn iconfont sec-color">&#xe611;</i>
    </div>
    <div class="slogan">
        <i class="en iconfont default-color">&#xe612;</i>
    </div>
    <div class="menu">
        <a href="/" class="default-color">首页</a>
        <a href="web.html" class="default-color">Web</a>
        <a href="#" class="default-color">App</a>
        <a href="#" class="default-color">服务</a>
        <a href="#" class="default-color">关于我们</a>
    </div>
</div>