<link href="styles/layout.css" rel="stylesheet" type="text/css" />
<link href="styles/icons.css" rel="stylesheet" type="text/css" />
<link href="styles/theme.css" rel="stylesheet" type="text/css" />
<link href="styles/owl.carousel.min.css" rel="stylesheet" type="text/css" />
<link href="styles/owl.theme.default.min.css" rel="stylesheet" type="text/css" />
<link href="styles/animation.css" rel="stylesheet" type="text/css" />
<script src="js/jquery.js"></script>
<script src="js/owl.carousel.min.js"></script>